name: maya_smart_home
description: "Maya Smart Home mobile app - BLE provisioning and 3-channel relay control."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
